# -*- coding: utf-8 -*-
"""tarea 3 python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTmQOBDjcskBlJoyLvM2_0QFsfm0AR7o

# Título del reto: Diseñar un flujo analítico reproducible

Se han obtenido bases de datos provenientes del Ministerio de Educación y del Instituto Nacional de Estadística y Censos (INEC). Para su integración, es necesario realizar una revisión y validación previa de las variables disponibles, con el fin de identificar aquellas que permitan establecer una clave común y garantizar una adecuada unión entre las diferentes fuentes de información.
"""

## Carga de paquetes

import os
import sys
import hashlib
import json
from datetime import datetime
from pathlib import Path
import pandas as pd
import numpy as np

"""## ** Creación de Rutas**"""

base_tarea = Path("tarea_educacion")
raw_path = base_tarea / "data" / "raw"
proc_path = base_tarea / "data" / "processed"
raw_path.mkdir(parents=True, exist_ok=True)
proc_path.mkdir(parents=True, exist_ok=True)

"""# **4. Catálogo oficial de provincias**"""

catalogo_provincias = pd.DataFrame({
    "cod_provincia": [
        "01", "02", "03", "04", "05", "06", "07", "08",
        "09", "10", "11", "12", "13", "14", "15", "16",
        "17", "18", "19", "20", "21", "22", "23", "24", "90"
    ],
    "provincia": [
        "Azuay",
        "Bolívar",
        "Cañar",
        "Carchi",
        "Cotopaxi",
        "Chimborazo",
        "El Oro",
        "Esmeraldas",
        "Guayas",
        "Imbabura",
        "Loja",
        "Los Ríos",
        "Manabí",
        "Morona Santiago",
        "Napo",
        "Pastaza",
        "Pichincha",
        "Tungurahua",
        "Zamora Chinchipe",
        "Galápagos",
        "Sucumbíos",
        "Orellana",
        "Santo Domingo",
        "Santa Elena",
        "Zona en estudio"
    ]
})

catalogo_provincias.to_csv(
    raw_path / "catalogo_provincias.csv",
    index=False,
    encoding="utf-8"
)

print(" Datos de prueba generados en `tarea_educacion/data/raw/`.")

"""# **2. LECTURA CONTROLADA**

Esta etapa permite cargar las diferentes fuentes de información de manera controlada, especificando el formato, separador, codificación y tipo de datos de las variables. Esto facilita una correcta interpretación de la información y prepara las bases para su posterior validación, transformación e integración.
"""

df_empleados = pd.read_excel(
    raw_path / "empleados.xlsx",
    dtype={"cod_prov": str}
)

df_socioeco = pd.read_csv(
    raw_path / "socioeconomico.csv",
    sep=";",
    dtype={"cod_prov": str},
    encoding="utf-8",
)



with open(raw_path / "educacion.json", "r", encoding="utf-8") as f:
    datos_educacion = json.load(f)

df_educacion = pd.json_normalize(datos_educacion)

print(df_empleados )
print(df_socioeco )
print(df_educacion )

"""#3. CONTRATO DE CALIDAD

Esta etapa permite verificar que cada fuente cumpla con los requisitos mínimos de calidad antes de su integración. Se comprueba la existencia de las variables requeridas y que la variable utilizada como clave de unión no presente valores duplicados ni nulos, garantizando así una integración confiable de las bases de datos.
"""

print(df_empleados.columns)
print(df_socioeco.columns)
print(df_educacion.columns)

def validar_informacion(df: pd.DataFrame, nombre_fuente: str, columnas_requeridas: set, col_clave: str):
  errores = []

  faltantes = columnas_requeridas - set(df.columns)
  if faltantes:
    errores.append(f"Faltan columnas requeridas: {faltantes}")

  if col_clave in df.columns:
    if df[col_clave].duplicated().any():
        dups = df[col_clave][df[col_clave].duplicated()].tolist()
        errores.append(f"Claves duplicadas detectadas en {col_clave}: {dups}")
    if df[col_clave].isnull().any():
        errores.append(f"Existen valores nulos en la clave {col_clave}")

  if errores:
    raise ValueError(f" FALLÓ CONTRATO DE DATOS [{nombre_fuente}]: {'; '.join(errores)}")

  print(f" Contrato validado con éxito para [{nombre_fuente}] ({len(df)} registros)")
validar_informacion(df_socioeco, "socioeconomico CSV", {"cod_prov", "monto_prest", "tipo_cuot"}, "cod_prov")
validar_informacion(df_empleados, "empleados Excel", {"cod_prov", "total_empleados"}, "cod_prov")
validar_informacion(df_educacion, "educación JSON", {"Cod_Prov", "Zonal", "Total_Docentes",
       "Total_Estudiantes"}, "Cod_Prov")

"""# 4. INTEGRACIÓN DE DATASET

En esta etapa se homogeneizan las variables clave de las diferentes fuentes para garantizar que puedan ser integradas correctamente. Primero, se unifica el nombre de la variable de identificación territorial como cod_provincia. Posteriormente, se estandariza su formato a dos dígitos, de acuerdo con la codificación de la División Político-Administrativa (DPA), mediante el uso de zfill(2). Esto permite que los códigos provinciales mantengan una estructura uniforme y sean utilizados como clave común para la integración de las bases.

Se va a renombrar las variables que se usara como ID codigo provincia.
"""

df_empleados = df_empleados.rename(columns={"cod_prov": "cod_provincia"})
df_socioeco = df_socioeco.rename(columns={"cod_prov": "cod_provincia"})
df_educacion = df_educacion.rename(columns={"Cod_Prov": "cod_provincia"})
df_educacion = df_educacion.rename(columns={"Cod_Prov": "cod_provincia"})

"""Se estandariza la variable cod_provincia a dos digitos como se establece en la DPA"""

df_empleados["cod_provincia"] = df_empleados["cod_provincia"].astype(str).str.zfill(2)
df_socioeco["cod_provincia"] = df_socioeco["cod_provincia"].astype(str).str.zfill(2)
df_educacion["cod_provincia"] = df_educacion["cod_provincia"].astype(str).str.zfill(2)

"""Se realiza la integración progresiva de las diferentes fuentes utilizando cod_provincia como clave común de unión. Se emplea un left join tomando como base el catálogo de provincias, con el propósito de conservar todas las provincias registradas en el catálogo e incorporar la información disponible de las bases de empleados, socioeconómica y educación.

Asimismo, mediante indicator se generan variables de control (_merge_empleo, _merge_prestamo y _merge_educacion) que permiten identificar posteriormente si los registros de cada fuente fueron correctamente vinculados al consolidado.
"""

merge_1 = catalogo_provincias.merge(
    df_empleados,
    on="cod_provincia",
    how="left",
    indicator="_merge_empleo"
)

merge_2 = merge_1.merge(
    df_socioeco,
    on="cod_provincia",
    how="left",
    indicator="_merge_prestamo"
)

consolidado = merge_2.merge(
    df_educacion,
    on="cod_provincia",
    how="left",
    indicator="_merge_educacion"
)

"""Esta etapa permite verificar el resultado de las uniones realizadas entre las bases de datos. Mediante las variables de control generadas con indicator, se identifica cuántos registros del catálogo de provincias encontraron correspondencia en cada fuente y cuáles no presentaron coincidencias. Esto permite detectar posibles inconsistencias o ausencia de información antes de continuar con el análisis."""

print("AUDITORÍA DE COINCIDENCIAS")
print("\n")
print("Presencia en empleo:")
print(consolidado["_merge_empleo"].value_counts())
print("\n")
print("Presencia en socioeconomico:")
print(consolidado["_merge_prestamo"].value_counts())
print("Presencia en educacion:")
print(consolidado["_merge_educacion"].value_counts())

"""Una vez finalizada la auditoría de coincidencias, se eliminan las columnas auxiliares de control generadas durante los merge (_merge_). Estas variables fueron utilizadas únicamente para verificar la correcta integración de las fuentes, por lo que no son necesarias en la base final.


"""

columnas_indicadoras = [c for c in consolidado.columns if c.startswith("_merge_")]
consolidado_limpio = consolidado.drop(columns=columnas_indicadoras)

display(consolidado_limpio)

"""Solo mantenemos la variable de provincia de la base de catalogo"""

consolidado_limpio = consolidado_limpio.drop(columns=["Provincia_x", "Provincia_y","Provincia"], errors="ignore")

display(consolidado_limpio)

"""Verificamos en que variables existe NA"""

consolidado_limpio.isnull().sum()

"""En esta etapa se identifican y tratan los valores faltantes de las variables seleccionadas. Para monto_pres los valores NaN se reemplazan por 0, y las de tipo categorica tipo_cuot con "sin información", con el propósito de evitar valores ausentes en el consolidado final"""

consolidado_limpio["monto_prest"] = consolidado_limpio["monto_prest"].fillna(0)

consolidado_limpio["tipo_cuot"] = consolidado_limpio["tipo_cuot"].fillna("Sin información")
display(consolidado_limpio)

"""# **6. Variable Derivada**

Se calcula la tasa de docentes por cada 100 estudiantes, relacionando el número total de docentes con el número total de estudiantes. Se utiliza np.where para evitar divisiones por cero en los casos en que no existan estudiantes registrados.
"""

consolidado_limpio["tasa_docente_estu"] = np.where(
    consolidado_limpio["Total_Estudiantes"] > 0,
    (consolidado_limpio["Total_Docentes"] / consolidado_limpio["Total_Estudiantes"]) * 100,
    0.0
)
print("Tasa de docentes por estudiante:")
print(consolidado_limpio["tasa_docente_estu"])

"""# **7. Auditoria**

En esta etapa se guardan los resultados del procesamiento en formatos CSV y Excel, organizados en las carpetas correspondientes de datos procesados y productos finales. Posteriormente, se calcula el hash SHA-256 de cada archivo generado, lo que permite verificar su integridad y detectar posibles modificaciones posteriores a su generación.

Además, la función calcular_sha256() garantiza que cada archivo tenga una huella digital única que puede utilizarse para fines de trazabilidad y control de los resultados.
"""

from pathlib import Path

processed_path = Path("/content/drive/MyDrive/taller_educacion/data/processed")
outputs_path = Path("/content/drive/MyDrive/taller_educacion/data/outputs")

processed_path.mkdir(parents=True, exist_ok=True)
outputs_path.mkdir(parents=True, exist_ok=True)

ruta_salida_csv = processed_path / "consolidado_provincial_informacion_202601.csv"
ruta_salida_excel = outputs_path / "tablero_indicadores_informacion_202601.xlsx"

consolidado_limpio.to_csv(
    ruta_salida_csv,
    index=False,
    encoding="utf-8"
)

consolidado_limpio.to_excel(
    ruta_salida_excel,
    index=False
)

def calcular_sha256(ruta_archivo: Path) -> str:
  hasher = hashlib.sha256()
  with open(ruta_archivo, "rb") as f:
    hasher.update(f.read())
  return hasher.hexdigest()

hash_csv = calcular_sha256(ruta_salida_csv)
hash_excel = calcular_sha256(ruta_salida_excel)

"""El manifiesto permite mantener una trazabilidad básica del procesamiento y de los archivos generados, facilitando su identificación y posterior verificación."""

import json

manifiesto = {
    "archivo_procesado": ruta_salida_csv.name,
    "archivo_excel": ruta_salida_excel.name,
    "filas_totales": len(consolidado_limpio),
    "columnas_totales": len(consolidado_limpio.columns),
    "sha256_csv": hash_csv,
    "sha256_excel": hash_excel
}

ruta_manifiesto = outputs_path / "manifiesto_ejecucion.json"

with open(ruta_manifiesto, "w", encoding="utf-8") as f:
    json.dump(
        manifiesto,
        f,
        ensure_ascii=False,
        indent=4
    )

print(f"Manifiesto guardado en: {ruta_manifiesto}")

print(" Proceso finalizado con éxito.")
print(f" - CSV SHA256: {hash_csv}")
print(f" - EXCEL SHA256: {hash_excel}")
print(f" - Manifiesto guardado en: {ruta_manifiesto}")

"""Esta etapa confirma la finalización exitosa del flujo de procesamiento y presenta los principales elementos de control generados. Se muestran los códigos SHA-256 correspondientes a los archivos CSV y Excel, así como la ubicación del manifiesto de ejecución, permitiendo verificar y mantener la trazabilidad de los productos finales."""